# Generated by Django 4.2.8 on 2023-12-13 13:43

import django.core.validators
from django.db import migrations, models
import fruitipedia_app.web_fruitipedia_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_fruitipedia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_app.web_fruitipedia_app.models.validate_name_should_contain_only_letters])),
                ('fruit_image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
