# Generated by Django 4.2.9 on 2024-01-10 15:52

import car_collection_app.web_car_collection_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_car_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[car_collection_app.web_car_collection_app.models.valid_year_validator]),
        ),
    ]
