# Generated by Django 4.2.10 on 2024-02-08 08:19

import django.core.validators
from django.db import migrations, models
import eventer_app.web_eventer_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[eventer_app.web_eventer_app.models.first_name_consist_only_letter])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), eventer_app.web_eventer_app.models.password_must_contain_one_digit])),
            ],
        ),
    ]
