# Generated by Django 4.2.10 on 2024-02-08 09:02

import django.core.validators
from django.db import migrations, models
import eventer_app.web_eventer_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_eventer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')])),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[eventer_app.web_eventer_app.models.date_validation])),
                ('event_image', models.URLField()),
            ],
        ),
    ]
