# Generated by Django 4.2.8 on 2023-12-17 15:44

import django.core.validators
from django.db import migrations, models
import expenses_tracker_app.web_expenses_tracker_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[expenses_tracker_app.web_expenses_tracker_app.models.MaxFileSizeInMBValidator(5)])),
            ],
        ),
    ]
